### ISSUE TITLE
return Tuple for App::Response

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/salt#1]
In rack, it use array as response, and make it simple and less code to use:

```crystal
class Talk < Salt::App
  def call(env)
    [200, { "Content-Type" => "text/plain" }, ["Can I talk to salt?"]]
  end
end
```

in PL [#275](https://github.com/veelenga/awesome-crystal/pull/275) by @RX14 suggested use tuples instead of array, but more code to use.

```crystal
class Talk < Salt::App
  def call(env)
    {
      status_code: 400,
      headers: { "Content-Type" => "text/plain" },
      body: ["Can I talk to salt?"]
    }
  end
end
```

Which is better?

**Comment by icyleaf** [comment]
it was done with tuples version: https://github.com/icyleaf/salt/tree/refactor-app-response-return-with-namedtuple

**Comment by RX14** [comment]
tuples != named tuples

```cr
class Talk < Salt::App
  def call(env)
    {200, { "Content-Type" => "text/plain" }, {"Can I talk to salt?"}}
  end
end
```

should work, so should

```cr
class Talk < Salt::App
  def call(env)
    {200, {"Content-Type": "text/plain" }, "Can I talk to salt?"}
  end
end
```

The last example returns values entirely on the stack, requiring no heap allocations. This helps performance a lot.

Using a tuple instead of an array is far more type safe too.

**Comment by icyleaf** [comment]
Sorry, i got wrong.
