### ISSUE TITLE
env.session raises NotFoundMiddleware

### ISSUE THREAD

**Issue by tuplebunny** [icyleaf/salt#3]
Setup:

```
salt-bug $ crystal -v
Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

salt-bug $ cat salt-bug.cr
require "salt"
require "salt/middlewares/session/cookie"

class App < Salt::App
  def call(env)
    {200, {"Content-Type" => "text/plain"}, ["OK"]}
  end
end

Salt.use(Salt::Session::Cookie, secret: "...")

Salt.run(App.new)

salt-bug $ crystal salt-bug.cr 
[11724] Salt server starting ...
[11724] * Version 0.4.2 (Crystal 0.27.0)
[11724] * Environment: development
[11724] * Listening on http://localhost:9898/
[11724] Use Ctrl-C to stop
```

Visit localhost:9898 in browser...

```
Salt::Exceptions::NotFoundMiddleware at /
Missing Session middleware, use Salt::run add it.
```

Server output:

```
Salt::Exceptions::NotFoundMiddleware: Missing Session middleware, use Salt::run add it.
    lib/salt/src/salt/environment.cr:0:9 in 'session'
    lib/salt/src/salt/middlewares/session/abstract/persisted.cr:35:7 in 'call'
    ...
```

I modified `persisted.cr#call` like:

```
def call(env)
  prepare_session(env)

  # Force exception here:
  env.session # raises Exceptions::NotFoundMiddleware.new("...")

  call_app(env)
  commit_session(env)

  {status_code, headers, body}
end
```

Inside `prepare_session`, calling `session` and even `env.session` is okay; seems only after exiting `prepare_session` does calling `env.session` raise the above exception.

This is my first bug-report ever, so please lemme know if you need anything else.

Also, thank-you for writing Salt. I've spent many hours learning Rack, and it's cool to see some of that experience be of use learning Salt.

**Comment by tuplebunny** [comment]
Oh, one other thing... Crystal 0.27.0 introduced a breaking-change to Tempfile -- I had to modify Salt's source to remove references to Tempfile... Lemme see if I can find my changes...

In `environment.cr`:

1. Remove reference to `require "tempfile"`.
1. `getter tempfile : File`
1. `@tempfile = File.tempfile(@filename)`

Those were the 3 changes I remember making.

**Comment by icyleaf** [comment]
Thanks for feedback, It was strange bug with `env.session raises NotFoundMiddleware`.

**Comment by tuplebunny** [comment]
My pleasure.

I'm taking another stab at the exception now.

**Comment by icyleaf** [comment]
My mistake, i use `struct` instead of `class` to define `Enviroment`.

**Comment by icyleaf** [comment]
You can try release v`0.4.3`

**Comment by tuplebunny** [comment]
Ah, and structs are immutable in Crystal, yeah?

Edit - No they're not; https://crystal-lang.org/docs/syntax_and_semantics/structs.html

**Comment by icyleaf** [comment]
A struct is a value type (it extends from Value) and when you invoke #new it is allocated on the stack. It is passed and assigned by value (copy). It doesn't have an object_id.

**Comment by tuplebunny** [comment]
Okay. I updated to Salt 0.4.3, and the sample-app from above no longer exhibits the previous error.

I can successfully-use `env.session.set`, etc.

And I see through cURL that the cookie looks encrypted.

Thanks so much, icyleaf.

**Comment by icyleaf** [comment]
Welcome any issues :)
